# Generated by Django 5.1.2 on 2024-10-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name_plural': 'Me'},
        ),
    ]
