# Generated by Django 5.1.2 on 2024-10-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_me_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('github', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.person')),
            ],
            options={
                'verbose_name_plural': 'Me',
            },
        ),
        migrations.DeleteModel(
            name='Me',
        ),
    ]
