# Generated by Django 5.1.2 on 2024-10-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_meme_delete_me'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeMe',
            new_name='Me',
        ),
    ]
