# Generated by Django 5.1.2 on 2024-10-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_page',
            field=models.BooleanField(default=True),
        ),
    ]
