# Generated by Django 5.1.2 on 2024-10-29 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('teaching', '0002_remove_course_instructor_alter_course_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='home.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='home.location'),
        ),
        migrations.AlterField(
            model_name='course',
            name='office_hour',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
