# Generated by Django 5.1.2 on 2024-10-31 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('teaching', '0002_alter_course_create_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='home.person'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='home.location'),
        ),
        migrations.AlterField(
            model_name='course',
            name='reading',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='teaching.reading'),
        ),
    ]
