# Generated by Django 5.1.2 on 2024-10-29 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0003_course_instructor_alter_course_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='identifier',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('due_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework', to='teaching.course')),
            ],
        ),
    ]
