# Generated by Django 5.1.2 on 2024-10-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0004_course_identifier_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/pdfs/'),
        ),
        migrations.RemoveField(
            model_name='homework',
            name='course',
        ),
        migrations.AddField(
            model_name='homework',
            name='course',
            field=models.ManyToManyField(related_name='homework', to='teaching.course'),
        ),
    ]
