# Generated by Django 5.1.2 on 2024-10-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_course_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
