# Generated by Django 5.1.2 on 2024-12-08 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='conference', to='home.location')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='education', to='home.location')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=60)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment', to='home.location')),
            ],
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentoring', to='home.location')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('journal', models.CharField(blank=True, max_length=60)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('article', models.CharField(blank=True, max_length=120)),
                ('volume', models.CharField(blank=True, max_length=120)),
                ('issue', models.CharField(blank=True, max_length=120)),
                ('doi', models.CharField(blank=True, max_length=120)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tag', models.ManyToManyField(blank=True, default=None, related_name='publications', to='home.tag')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.publication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='publications', through='cv.PublicationPerson', to='home.person'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='service', to='home.location')),
            ],
        ),
        migrations.CreateModel(
            name='TalkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, max_length=60)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='home.location')),
                ('talk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='cv.talk')),
            ],
        ),
    ]
