# Generated by Django 5.1.2 on 2024-10-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='publications', to='home.person'),
        ),
    ]
