# Generated by Django 5.1.2 on 2024-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preprint',
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
