# Generated by Django 5.1.2 on 2024-10-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='people',
        ),
        migrations.CreateModel(
            name='PublicationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.person')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.publication')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
