# Generated by Django 5.1.2 on 2024-10-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_delete_preprint_alter_education_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
