# Generated by Django 5.1.2 on 2024-10-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_publication_people_publicationperson'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='publications', through='cv.PublicationPerson', to='home.person'),
        ),
    ]
