# Generated by Django 5.1.2 on 2024-10-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_publication_people'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='conference', to='home.location'),
        ),
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='education', to='home.location'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='employment', to='home.location'),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentoring', to='home.location'),
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tag',
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='service', to='home.location'),
        ),
        migrations.AlterField(
            model_name='talkdetail',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='home.location'),
        ),
        migrations.AlterField(
            model_name='talkdetail',
            name='talk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='cv.talk'),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching', to='home.location'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, related_name='publications', to='home.tag'),
        ),
    ]
