# Generated by Django 5.1.2 on 2024-10-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_employment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='notes',
        ),
        migrations.AddField(
            model_name='employment',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
