# Generated by Django 5.1.2 on 2024-10-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_conference_location_alter_education_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
