# Generated by Django 5.1.2 on 2024-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_conference_location_conference_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
        migrations.AddField(
            model_name='service',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
