# Generated by Django 5.1.2 on 2024-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_publicationperson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationperson',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
