# Generated by Django 5.1.2 on 2024-10-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_employment_notes_employment_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='note',
            new_name='article',
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
