# Generated by Django 5.1.2 on 2024-10-29 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_rename_note_publication_article_publication_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='cv.location'),
        ),
    ]
