# Generated by Django 5.1.2 on 2024-10-31 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_publicationperson_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teaching',
        ),
    ]
