# Generated by Django 5.1.2 on 2024-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_person_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='people',
        ),
        migrations.AddField(
            model_name='publication',
            name='people',
            field=models.ManyToManyField(related_name='publications', to='cv.person'),
        ),
    ]
