# Generated by Django 5.1.2 on 2024-10-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_remove_publication_people_publication_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='date',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='location',
        ),
        migrations.CreateModel(
            name='TalkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='cv.location')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='cv.talk')),
            ],
        ),
    ]
