# Generated by Django 5.1.2 on 2024-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_remove_talk_date_remove_talk_location_talkdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkdetail',
            name='note',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
